import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';import {uvLayout,uvSVG,textureEntries} from '../src/uv.js';
function fixture(indexed=true){const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute([0,0,0,1,0,0,0,1,0,1,1,0],3));g.setAttribute('uv',new T.Float32BufferAttribute([0,0,1,0,0,1,1,1],2));g.setIndex([0,1,2,1,3,2]);const texture=new T.Texture({width:64,height:32});texture.flipY=false;const mesh=new T.Mesh(indexed?g:g.toNonIndexed(),new T.MeshStandardMaterial({map:texture}));const group=new T.Group();group.add(mesh);return textureEntries(group)[0];}
test('UV export preserves GLTF image orientation and handles indexed/nonindexed meshes',()=>{const a=uvLayout(fixture()),b=uvLayout(fixture(false));assert.deepEqual(a,b);assert.deepEqual(a.triangles[0],[[0,0],[1,0],[0,1]]);assert.equal(a.edges.length,4);assert.match(uvSVG(a,64,32),/M0.000,0.000L64.000,0.000/);assert.ok(!a.edges.some(e=>e.some(p=>p[0]===1&&p[1]===0)&&e.some(p=>p[0]===0&&p[1]===1)),'internal diagonal must not be drawn');});
test('UV export respects material groups, texture channels and transforms',()=>{const e=fixture();e.mesh.material=[e.material,e.material.clone()];e.mesh.geometry.addGroup(0,3,0);e.mesh.geometry.addGroup(3,3,1);e.materialIndex=1;assert.equal(uvLayout(e).triangles.length,1);e.texture.channel=1;assert.equal(uvLayout(e).triangles.length,0);e.mesh.geometry.setAttribute('uv1',e.mesh.geometry.attributes.uv.clone());e.texture.offset.x=.5;e.texture.flipY=true;const result=uvLayout(e);assert.deepEqual(result.triangles[0][0],[1.5,1]);assert.equal(result.outside,true);});
test('coincident UV triangles are reported without dropping their lines',()=>{const e=fixture();e.mesh.geometry.setIndex([0,1,2,2,1,0]);const layout=uvLayout(e);assert.equal(layout.overlaps,1);assert.equal(layout.triangles.length,2);assert.equal(layout.edges.length,3);});

test('UV seams remain outlined across split vertices',()=>{const e=fixture(false),uv=e.mesh.geometry.attributes.uv;for(let i=3;i<6;i++)uv.setX(i,uv.getX(i)+2);assert.equal(uvLayout(e).edges.length,6);});

import {islandPieces,packIslands} from '../src/uv-islands.js';
test('islands join shared topology, preserve seams and pack without overlaps',()=>{const joined=uvLayout(fixture(false));assert.equal(joined.islands.length,1);const e=fixture(false);e.mesh.geometry.attributes.uv.setXY(3,.2,.2);const layout=uvLayout(e);assert.equal(layout.islands.length,2);const pieces=islandPieces(layout,64,32),packed=packIslands(pieces);assert.equal(packed.pieces.length,2);const [a,b]=packed.pieces;assert.ok(a.displayX+a.width<b.displayX||b.displayX+b.width<a.displayX||a.displayY+a.height<b.displayY||b.displayY+b.height<a.displayY);assert.deepEqual(pieces.map(p=>[p.x,p.y]),packed.pieces.sort((a,b)=>a.id-b.id).map(p=>[p.x,p.y]));});
