export function createHandsPanel(actions){
 const panel=document.createElement('details');panel.className='inspector-disclosure hands-panel';panel.innerHTML=`<summary>Mãos · punhos</summary><button id="add-hands" class="wide">Adicionar rig das mãos</button><div id="hand-controls" hidden>
 <label class="grip-field">Fechar mão esquerda <output id="grip-L-value">0%</output><input id="grip-L" type="range" min="0" max="100" value="0" aria-label="Fechar mão esquerda"/></label>
 <label class="grip-field">Fechar mão direita <output id="grip-R-value">0%</output><input id="grip-R" type="range" min="0" max="100" value="0" aria-label="Fechar mão direita"/></label>
 <label class="field-row">Aplicar pose<select id="hand-preset-side"><option value="both">Ambas</option><option value="L">Esquerda</option><option value="R">Direita</option></select></label><div class="hand-presets"><button data-grip="0">Aberta</button><button data-grip=".25">Relaxada</button><button data-grip="1">Punho</button></div><p class="muted">Adicione um keyframe para gravar esta pose.</p>
 <details class="inspector-disclosure"><summary>Ajustar rig das mãos</summary><label class="field-row">Mão<select id="hand-fit-side"><option value="L">Esquerda</option><option value="R">Direita</option></select></label><button id="focus-hand" class="wide">Enquadrar mão</button>
 <label class="field-row">Comprimento (cm)<input id="hand-length" type="number" min="5" max="40" step=".5"/></label><label class="field-row">Largura (cm)<input id="hand-width" type="number" min="2" max="25" step=".5"/></label><label class="field-row">Base dos dedos (%)<input id="hand-palm" type="number" min="15" max="70" step="1"/></label><label class="field-row">Orientação (graus)<input id="hand-roll" type="number" min="-360" max="360" step="5"/></label><label class="field-row">Centro lateral (cm)<input id="hand-shift" type="number" min="-20" max="20" step=".1"/></label><label class="field-row">Profundidade (cm)<input id="hand-depth" type="number" min="-20" max="20" step=".1"/></label><label class="field-row">Direção (graus)<input id="hand-yaw" type="number" min="-85" max="85" step="5"/></label><label class="field-row">Inclinação (graus)<input id="hand-pitch" type="number" min="-85" max="85" step="5"/></label><label class="field-row">Início da palma (cm)<input id="hand-start" type="number" min="-20" max="20" step=".5"/></label><label class="field-row">Lado do polegar<select id="hand-thumb"><option value="-1">A</option><option value="1">B</option></select></label><label class="field-row">Base do polegar (%)<input id="hand-thumb-start" type="number" min="-50" max="70" step="1"/></label><label class="field-row">Tamanho do polegar (%)<input id="hand-thumb-length" type="number" min="10" max="100" step="1"/></label><button id="estimate-hands" class="wide">Estimar novamente</button><button id="fit-hands" class="wide">Aplicar ajuste das mãos</button><p class="muted">Confira as linhas dos dedos na mão aberta. Ajustar recalcula os pesos dos dedos; os pesos do corpo são mantidos.</p></details></div><p id="hands-help" class="muted">Requer dedos modelados. O rig estima a posição inicial; confira o alinhamento antes de fechar.</p>`;
 document.querySelector('#inspector-page-pose').append(panel);
 const $=s=>panel.querySelector(s);let saved=null;
 $('#add-hands').onclick=actions.enable;$('#estimate-hands').onclick=actions.enable;
 for(const side of ['L','R']){
  const input=$(`#grip-${side}`);let started=false;
  input.addEventListener('input',()=>{if(!started){actions.record();started=true;}actions.grip(side,Number(input.value)/100);});
  input.addEventListener('change',()=>{started=false;});input.addEventListener('blur',()=>{started=false;});
 }
 panel.querySelectorAll('[data-grip]').forEach(b=>b.onclick=()=>{actions.record();const side=$('#hand-preset-side').value;for(const s of side==='both'?['L','R']:[side])actions.grip(s,Number(b.dataset.grip));});
 function fitFields(){if(!saved)return;const c=saved[$('#hand-fit-side').value];$('#hand-thumb-start').value=Math.round((c.thumbStart??.28)*100);$('#hand-thumb-length').value=Math.round((c.thumbLength??.6)*100);$('#hand-length').value=(c.length*100).toFixed(1);$('#hand-width').value=(c.width*100).toFixed(1);$('#hand-palm').value=Math.round(c.palm*100);$('#hand-roll').value=Math.round(c.roll*180/Math.PI);$('#hand-shift').value=((c.shift||0)*100).toFixed(1);$('#hand-depth').value=((c.depth||0)*100).toFixed(1);for(const k of ['yaw','pitch'])$('#hand-'+k).value=Math.round((c[k]||0)*180/Math.PI);$('#hand-start').value=((c.start||0)*100).toFixed(1);$('#hand-thumb').value=String(c.thumbSide||($('#hand-fit-side').value==='L'?-1:1));}
 $('#hand-fit-side').onchange=fitFields;$('#focus-hand').onclick=()=>actions.focus($('#hand-fit-side').value);
 $('#fit-hands').onclick=()=>{const config=structuredClone(saved),side=$('#hand-fit-side').value;config[side]={thumbStart:Number($('#hand-thumb-start').value)/100,thumbLength:Number($('#hand-thumb-length').value)/100,length:Number($('#hand-length').value)/100,width:Number($('#hand-width').value)/100,palm:Number($('#hand-palm').value)/100,roll:Number($('#hand-roll').value)*Math.PI/180,shift:Number($('#hand-shift').value)/100,depth:Number($('#hand-depth').value)/100,yaw:Number($('#hand-yaw').value)*Math.PI/180,pitch:Number($('#hand-pitch').value)*Math.PI/180,start:Number($('#hand-start').value)/100,thumbSide:Number($('#hand-thumb').value)};actions.fit(config);};
 return {update(config,grips,busy){$('#add-hands').hidden=!!config;$('#hand-controls').hidden=!config;$('#hands-help').hidden=!!config;for(const s of ['L','R']){const input=$(`#grip-${s}`),value=Math.round((grips[s]||0)*100);if(document.activeElement!==input)input.value=value;$(`#grip-${s}-value`).textContent=value+'%';}if(JSON.stringify(config)!==JSON.stringify(saved)){saved=structuredClone(config);fitFields();}panel.querySelectorAll('input,select,button').forEach(el=>el.disabled=busy);}};
}
