import {paintInfluences} from './paint.js';
import './style.css';
import {generateWalk} from './walk.js';
import {generateIdle,generateRun} from './motion.js';
import * as THREE from 'three';
import {createIcons,ArrowRight,ArrowUpRight,Bone,Box,ChevronRight,Clapperboard,ClipboardPaste,Copy,Crosshair,DiamondPlus,FolderOpen,Grid2x2,Hand,Image,Move,Pause,PersonStanding,Play,Redo2,Repeat2,Rotate3d,RotateCcw,RotateCw,Save,Scan,Settings2,SkipBack,Sparkles,Square,Trash2,Triangle,Undo2,Upload,X} from 'lucide';
const icons={ArrowRight,ArrowUpRight,Bone,Box,ChevronRight,Clapperboard,ClipboardPaste,Copy,Crosshair,DiamondPlus,FolderOpen,Grid2x2,Hand,Image,Move,Pause,PersonStanding,Play,Redo2,Repeat2,Rotate3d,RotateCcw,RotateCw,Save,Scan,Settings2,SkipBack,Sparkles,Square,Trash2,Triangle,Undo2,Upload,X};
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {TransformControls} from 'three/addons/controls/TransformControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {createDemo} from './demo.js';
import {JOINTS,IK_CHAINS,defaultMarkers,buildSkeleton,segmentsFor,capturePose,applyPose,samplePose,makeClip,moveBoneWorld} from './rig.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const icon=name=>`<i data-lucide="${name}"></i>`;
const refs=[['01-cavaleiro-cristal','Cavaleiro de cristal'],['02-elfa-floresta','Elfa da floresta'],['03-orc-aventureiro','Orc aventureiro'],['04-maga-lunar','Maga lunar'],['05-guardia-brasa','Guardiã da brasa']];
$('#app').innerHTML=`
<div class="app-shell">
<header class="topbar"><div class="brand"><span class="brand-mark">${icon('bone')}</span>riglab<span class="badge">PROTOTYPE</span></div><div class="project-name">Estúdio / <strong id="project-title">Sentinela da floresta</strong></div><div class="top-actions"><button id="undo" title="Desfazer (Ctrl/⌘ Z)" aria-label="Desfazer">${icon('undo-2')}</button><button id="redo" title="Refazer (Ctrl/⌘ Shift Z)" aria-label="Refazer">${icon('redo-2')}</button><button id="open-project">${icon('folder-open')}Abrir projeto</button><button id="save-project">${icon('save')}Salvar</button><button class="primary" id="export">${icon('arrow-up-right')}Exportar GLB</button></div></header>
<nav class="workflow" aria-label="Etapas"><button class="step" data-stage="import"><span>1</span>Modelo</button>${icon('chevron-right')}<button class="step active" data-stage="rig"><span>2</span>Rigging</button>${icon('chevron-right')}<button class="step" data-stage="animate"><span>3</span>Animação</button><div class="note"><i class="dot"></i>Arquivos processados neste navegador</div></nav>
<main class="workspace"><aside class="panel left-panel">
<section class="panel-section"><h2 class="section-title">Cena <b>01</b></h2><div class="asset-card"><div class="asset-icon">${icon('person-standing')}</div><div><strong id="asset-name">Sentinela da floresta</strong><small id="asset-meta">Humanoide · malha de demonstração</small></div></div><button id="import" class="wide">${icon('upload')}Importar modelo GLB</button><button id="demo" class="wide subtle">${icon('box')}Carregar demonstração</button></section>
<section class="panel-section"><h2 class="section-title">Esqueleto <b id="bone-count">19 juntas</b></h2><div id="tree" class="tree"></div></section>
<section class="panel-section"><h2 class="section-title">Referências ${icon('image')}</h2><div class="reference-strip">${refs.map(([file,name],i)=>`<button data-reference="${i}" title="${name}"><img src="${import.meta.env.BASE_URL}references/${file}.jpg" alt="${name}"/></button>`).join('')}</div><p class="muted">Conceitos em pose A. Use um GLB para trabalhar em 3D.</p></section></aside>
<section class="viewport" id="viewport" aria-label="Editor 3D"><div class="view-top"><div class="view-title"><i></i><span id="view-name">Perspectiva</span><span style="color:#667778">/</span>Estúdio</div><span class="view-pill" id="view-state">AJUSTE DO ESQUELETO</span></div><div class="tool-rail"><button id="tool-rotate" title="Rotacionar osso (R)" aria-label="Rotacionar osso">${icon('rotate-3d')}</button><button id="tool-move" class="active" title="Mover articulação / IK (G)" aria-label="Mover articulação">${icon('move')}</button><hr/><button id="frame-camera" title="Enquadrar personagem (F)" aria-label="Enquadrar personagem">${icon('scan')}</button><button id="front-camera" title="Vista frontal" aria-label="Vista frontal">${icon('square')}</button></div><div class="view-settings"><button id="skeleton-toggle" class="active">${icon('bone')}Esqueleto</button><button id="wire-toggle">${icon('triangle')}Malha</button><button id="weights-toggle" aria-pressed="false" title="Mostrar influência do osso selecionado">${icon('paintbrush')}Pesos</button><button id="grid-toggle" class="active">${icon('grid-2x2')}Grade</button></div><div id="weight-legend" class="weight-legend hidden"><strong id="weight-joint"></strong><div class="weight-gradient"></div><div class="weight-scale"><span>0% · sem influência</span><span>100%</span></div><small>Selecione um osso para inspecionar seus pesos.</small></div><div class="hint-card" id="hint">Ajuste as articulações e gere o rig para começar</div><div class="view-bottom"><span>Arraste para orbitar · Scroll para aproximar<br/>Clique em uma articulação para editar</span><span class="axes"><b style="color:#cb8b82">X</b> <b style="color:#b9d888">Y</b> <b style="color:#7fa7c2">Z</b></span></div><div id="busy" class="busy-overlay hidden"><div class="spinner"></div><span id="busy-label">Calculando pesos…</span></div></section>
<aside class="panel right-panel"><div class="inspector-head"><span class="eyebrow" id="inspector-kicker">02 / RIGGING ASSISTIDO</span><h2 id="inspector-title">Dê estrutura à ideia.</h2><p class="muted" id="inspector-description">Um esqueleto simples. Infinitas poses.</p></div>
<div id="import-panel" class="panel-section hidden"><h3 class="section-title">Preparar modelo</h3><p class="muted">Importe um humanoide em pose A ou T, com mãos afastadas do corpo. A altura é normalizada automaticamente.</p><button id="turn-model" class="wide">${icon('rotate-cw')}Girar 90° no eixo Y</button><button id="upright-model" class="wide">${icon('rotate-cw')}Girar 90° no eixo X</button><button id="start-rig" class="primary wide">Ajustar esqueleto ${icon('arrow-right')}</button></div>
<div id="rig-panel" class="panel-section"><h3 class="section-title">Configuração do rig</h3><div class="field-row"><span>Esqueleto</span><span style="color:#d1d9cc">Humanoide · 19 juntas</span></div><div class="field-row"><span>Pose de referência</span><select id="rest-type" aria-label="Pose de referência"><option value="A">A-pose</option><option value="T">T-pose</option></select></div><label class="field-row"><span>Largura dos braços</span><input id="rig-width" type="number" min="0.5" max="1.5" step=".05" value="1"/></label><label class="field-row"><span>Espelhar ajustes</span><input id="mirror" type="checkbox" checked/></label><button id="auto-rig" class="wide primary">${icon('sparkles')}Gerar auto-rig</button><div class="info-box"><strong>Confira antes de gerar</strong>Alinhe as juntas ao corpo, inclusive a profundidade. Os pesos combinam proximidade e uma transição protegida entre ombro, peito e pescoço.</div></div>
<div id="pose-panel" class="panel-section hidden"><h3 class="section-title">Controles de pose</h3><div class="segmented"><button id="fk-mode" class="active">Rotação / FK</button><button id="ik-mode">Mover</button></div><button id="neutral" class="wide">${icon('rotate-ccw')}Restaurar pose A/T</button><button id="wave" class="wide">${icon('hand')}Criar aceno de exemplo</button><div class="walk-generator"><h3 class="section-title">Gerador de caminhada</h3><label class="field-row"><span>Velocidade</span><select id="walk-speed"><option value="0.75">Lenta</option><option value="1" selected>Normal</option><option value="1.5">Rápida</option></select></label><label class="field-row"><span>Tamanho do passo</span><select id="walk-stride"><option value="0.18">Curto</option><option value="0.28" selected>Médio</option><option value="0.4">Longo</option></select></label><button id="walk" class="wide primary">${icon('play')}Gerar caminhada</button><p class="muted">Loop no lugar. Substitui o clipe atual; use Desfazer para recuperá-lo.</p></div><div class="walk-generator"><h3 class="section-title">Idle e corrida</h3><label class="field-row"><span>Expressividade</span><select id="motion-intensity"><option value="0.6">Sutil</option><option value="1" selected>Natural</option><option value="1.4">Expressiva</option></select></label><label class="field-row"><span>Ritmo</span><select id="motion-speed"><option value="0.8">Tranquilo</option><option value="1" selected>Normal</option><option value="1.25">Rápido</option></select></label><button id="idle" class="wide">${icon('person-standing')}Gerar idle</button><button id="run" class="wide primary">${icon('play')}Gerar corrida</button><p class="muted">Idle de espera: respiração, olhares, mão na cintura e mudança de apoio. Corrida com impulsão e fase aérea. Substitui o clipe; Desfazer recupera o anterior.</p></div><div class="walk-generator"><h3 class="section-title">Pintura de pesos</h3><button id="paint-toggle" class="wide" aria-pressed="false">Pintar pesos</button><div id="paint-options" class="hidden"><label class="field-row">Operação<select id="paint-operation"><option value="1">Adicionar</option><option value="-1">Remover</option></select></label><label class="field-row">Raio (cm)<input id="paint-radius" type="number" min="1" max="30" step="1" value="8"/></label><label class="field-row">Intensidade (%)<input id="paint-strength" type="number" min="1" max="100" value="20"/></label><button id="paint-undo" class="wide">Desfazer pincelada</button><p class="muted">Escolha o osso na lista e arraste sobre a malha. Botão direito: orbitar. Shift: inverte adicionar/remover. Recalcular pesos substitui a pintura.</p><p id="paint-feedback" class="muted" role="status"></p></div></div><button id="refine-weights" class="wide">${icon('sparkles')}Recalcular pesos</button><p class="muted">Refina ombros e pescoço, mantendo o rig e o clipe.</p><button id="edit-rig" class="wide subtle">${icon('settings-2')}Reajustar esqueleto</button></div>
<section class="panel-section"><h3 class="section-title">Articulação selecionada ${icon('crosshair')}</h3><select id="joint-select" style="width:100%" aria-label="Articulação selecionada">${JOINTS.map((j,i)=>`<option value="${i}">${j[1]}</option>`).join('')}</select><div class="field-row"><span id="transform-label">Posição · metros</span><span id="transform-space" class="muted">Global</span></div><div class="vector-fields">${['x','y','z'].map(a=>`<label>${a.toUpperCase()}<input id="axis-${a}" aria-label="Eixo ${a.toUpperCase()}" type="number" step="0.01" value="0"/></label>`).join('')}</div><p class="muted" id="joint-help">Arraste as setas no personagem ou ajuste os valores.</p></section>
<div class="inspector-footer"><div class="shortcut">Adicionar keyframe <kbd>K</kbd></div><div class="shortcut">Reproduzir / pausar <kbd>Espaço</kbd></div><div class="shortcut">Rotacionar / mover <kbd>R / G</kbd></div></div></aside></main>
<section class="timeline" aria-label="Timeline de animação"><div class="timeline-toolbar"><h3>${icon('clapperboard')}Animação <span id="clip-label">SEM CLIPE</span></h3><div class="transport"><button id="rewind" title="Voltar ao início" aria-label="Voltar ao início">${icon('skip-back')}</button><button id="play" title="Reproduzir (Espaço)" aria-label="Reproduzir">${icon('play')}</button><button id="loop" class="active" title="Alternar loop" aria-label="Alternar loop">${icon('repeat-2')}</button></div><span class="time-readout" id="time-readout">0.00 / 3.00 s</span><div class="timeline-actions"><label>Duração <input id="duration" type="number" min="0.4" max="30" value="3" step="0.1"/>s</label><button id="copy-key" title="Copiar pose atual">${icon('copy')}</button><button id="paste-key" title="Colar pose no tempo atual">${icon('clipboard-paste')}</button><button id="delete-key" title="Excluir keyframe selecionado">${icon('trash-2')}</button><button id="add-key">${icon('diamond-plus')}Keyframe <kbd>K</kbd></button></div></div><div class="timeline-body"><div class="track-labels"><div class="track-label">${icon('person-standing')}Pose do personagem<small id="key-count">0 poses</small></div></div><div class="timeline-grid" id="timeline-grid"><div class="ruler" id="ruler"></div><div class="key-track" id="key-track"></div><div class="playhead" id="playhead"></div><div class="timeline-help">Clique na régua para navegar · Arraste um losango para mover o keyframe · 30 fps</div></div></div></section>
<footer class="statusbar"><span class="ready" id="status">● Pronto</span><span id="stats"></span><span>RIGLAB 0.1 · LOCAL WORKSPACE</span></footer></div>
<input type="file" id="model-file" accept=".glb" hidden/><input type="file" id="project-file" accept=".riglab,.json" hidden/><div id="toast" class="toast hidden" role="status"></div><dialog id="reference-dialog"><div class="dialog-heading"><strong id="reference-title"></strong><button id="close-reference" aria-label="Fechar referência">${icon('x')}</button></div><img id="reference-image"/><p class="muted">Imagem conceitual de referência. A conversão da imagem em malha 3D é uma etapa externa.</p></dialog>`;
createIcons({icons});

const state={stage:'rig',selected:0,tool:'rotate',markers:defaultMarkers(),keys:[],time:0,duration:3,playing:false,loop:true,showSkeleton:true,wire:false,showWeights:false,painting:false,rigged:false,name:'Sentinela da floresta',busy:false};
let asset,model,skeleton,bindPose,bindMarkers=null,history=[],future=[],clipboard=null,toastTimer,sourceKind='demo',revision=0;
const viewport=$('#viewport'),scene=new THREE.Scene();scene.background=new THREE.Color('#262e30');scene.fog=new THREE.Fog('#262e30',8,20);
const camera=new THREE.PerspectiveCamera(35,1,.01,100);camera.position.set(2.65,1.9,5.3);
let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});}catch(e){$('#busy').classList.remove('hidden');$('#busy-label').textContent='WebGL indisponível. Abra em um navegador com aceleração gráfica.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;viewport.prepend(renderer.domElement);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,1,0);orbit.enableDamping=true;orbit.minDistance=.6;orbit.maxDistance=12;orbit.maxPolarAngle=Math.PI*.9;
scene.add(new THREE.HemisphereLight('#e4f5ed','#637275',2.6));
const keyLight=new THREE.DirectionalLight('#fff0d9',3.2);keyLight.position.set(3,6,4);keyLight.castShadow=true;keyLight.shadow.mapSize.set(2048,2048);keyLight.shadow.camera.left=-3;keyLight.shadow.camera.right=3;keyLight.shadow.camera.top=4;keyLight.shadow.camera.bottom=-3;keyLight.shadow.normalBias=.025;scene.add(keyLight);
const rim=new THREE.DirectionalLight('#c6eddf',2);rim.position.set(-3,3,-3);scene.add(rim);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:'#283234',roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.016;floor.receiveShadow=true;scene.add(floor);
const grid=new THREE.GridHelper(16,64,'#66716a','#3b494a');grid.material.opacity=.35;grid.material.transparent=true;grid.position.y=-.012;scene.add(grid);
const ring=new THREE.Mesh(new THREE.RingGeometry(1.04,1.045,96),new THREE.MeshBasicMaterial({color:'#849471',transparent:true,opacity:.4,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=-.008;scene.add(ring);
const rigVisual=new THREE.Group();scene.add(rigVisual);
const spheres=JOINTS.map((j,i)=>{const s=new THREE.Mesh(new THREE.SphereGeometry(.018,10,8),new THREE.MeshBasicMaterial({color:'#deefa7',depthTest:false,transparent:true,opacity:.88}));s.userData.index=i;s.renderOrder=11;rigVisual.add(s);return s;});
const lines=new THREE.LineSegments(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:'#c5d7a6',depthTest:false,transparent:true,opacity:.66}));lines.renderOrder=10;rigVisual.add(lines);
const gizmo=new TransformControls(camera,renderer.domElement);gizmo.setSize(.75);scene.add(gizmo.getHelper());
const ikTarget=new THREE.Object3D();scene.add(ikTarget);
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();
new ResizeObserver(()=>{const {width,height}=viewport.getBoundingClientRect();camera.aspect=width/height;camera.updateProjectionMatrix();renderer.setSize(width,height);}).observe(viewport);
function toast(message,error=false){$('#toast').textContent=message;$('#toast').className=`toast${error?' error':''}`;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),4500);}
function busy(on,label='Calculando pesos…'){state.busy=on;$('#busy').classList.toggle('hidden',!on);$('#busy-label').textContent=label;$$('button,input,select').forEach(b=>b.disabled=on);if(on)gizmo.detach();else updateUI();}
function materials(mesh){return Array.isArray(mesh.material)?mesh.material:[mesh.material];}
function disposeGroup(group,disposeTextures=false){if(!group)return;group.traverse(o=>{if(o.isMesh){o.geometry.dispose();materials(o).forEach(m=>{if(disposeTextures)Object.values(m).forEach(v=>{if(v?.isTexture)v.dispose();});m.dispose();});}});group.removeFromParent();}
function normalize(source){
 source.updateMatrixWorld(true);const group=new THREE.Group();let count=0;
 source.traverse(o=>{if(!o.isMesh)return;if(o.isSkinnedMesh)throw new Error('Importe uma malha sem rig. Esta versão gera um novo esqueleto.');if(o.isInstancedMesh)throw new Error('Instâncias não são suportadas. Exporte uma malha comum.');
 const g=o.geometry.clone();if(!g.attributes.position)return;count+=g.attributes.position.count;
 if(g.morphAttributes.position?.length)throw new Error('Exporte o modelo sem morph targets para este protótipo.');
 g.applyMatrix4(o.matrixWorld);const mat=materials(o).map(m=>{const n=m.clone();n.side=THREE.DoubleSide;return n;});const m=new THREE.Mesh(g,Array.isArray(o.material)?mat:mat[0]);m.name=`Mesh_${group.children.length}`;group.add(m);});
 if(!count)throw new Error('O arquivo não contém uma malha 3D.');if(count>200000)throw new Error('Limite do protótipo: 200 mil vértices. Simplifique a malha antes de importar.');
 const box=new THREE.Box3().setFromObject(group),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());if(![...size.toArray(),...center.toArray()].every(Number.isFinite))throw new Error('A malha contém coordenadas inválidas.');if(size.y<.00001)throw new Error('A malha não possui altura válida.');
 const scale=2/size.y,transform=new THREE.Matrix4().makeScale(scale,scale,scale).multiply(new THREE.Matrix4().makeTranslation(-center.x,-box.min.y,-center.z));
 group.children.forEach(m=>{m.geometry.applyMatrix4(transform);m.geometry.computeBoundingBox();});return group;
}
function replaceModel(rig=false){
 state.painting=false;paintUndo.length=0;gizmo.detach();clearWeightView();disposeGroup(model);skeleton?.dispose();model=new THREE.Group();model.name='RigLab_Character';scene.add(model);
 skeleton=rig?buildSkeleton(state.markers):null;
 if(skeleton)model.add(skeleton.bones[0]);
 asset.children.forEach((src,i)=>{const geometry=src.geometry.clone(),material=Array.isArray(src.material)?src.material.map(m=>m.clone()):src.material.clone();const mesh=rig?new THREE.SkinnedMesh(geometry,material):new THREE.Mesh(geometry,material);mesh.name=`Character_${i}`;mesh.castShadow=true;mesh.receiveShadow=true;mesh.frustumCulled=false;model.add(mesh);if(rig)mesh.bind(skeleton);materials(mesh).forEach(m=>m.wireframe=state.wire);});
 state.rigged=rig;if(rig){skeleton.calculateInverses();bindPose=capturePose(skeleton);bindMarkers=state.markers.map(p=>p.toArray());}else{bindMarkers=null;}updateVisual();
}
function loadAsset(newAsset,name,kind='import'){
 disposeGroup(asset,true);asset=newAsset;state.name=name;sourceKind=kind;state.markers=defaultMarkers();state.keys=[];state.time=0;state.playing=false;state.stage=kind==='demo'?'rig':'import';state.selected=0;state.tool='rotate';state.duration=3;$('#duration').value=3;$('#rest-type').value='A';$('#rig-width').value=1;history=[];future=[];replaceModel(false);frameCamera();updateUI();revision++;
}
// Keep inspection materials separate so saved/exported assets retain their appearance.
const paintUndo=[];let stroke=null,brushPointer=null;
const brushCursor=document.createElement('div');brushCursor.className='brush-cursor';brushCursor.hidden=true;$('#viewport').append(brushCursor);
function brushHit(e){
 const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);
 model.updateMatrixWorld(true);skeleton?.update();
 return raycaster.intersectObjects(model.children.filter(m=>m.isSkinnedMesh),false)[0];
}
function brushRadius(){return THREE.MathUtils.clamp(Number($('#paint-radius').value)||8,1,30)/100;}
function updateBrushCursor(){
 brushCursor.hidden=true;if(!state.painting||state.busy||!brushPointer)return;
 const hit=brushHit(brushPointer);if(!hit)return;
 const rect=renderer.domElement.getBoundingClientRect(),viewport=$('#viewport').getBoundingClientRect();
 const center=hit.point.clone().project(camera),edge=hit.point.clone().add(new THREE.Vector3().setFromMatrixColumn(camera.matrixWorld,0).multiplyScalar(brushRadius())).project(camera);
 const diameter=Math.abs(edge.x-center.x)*rect.width;
 brushCursor.style.width=brushCursor.style.height=`${diameter}px`;brushCursor.style.left=`${brushPointer.clientX-viewport.left}px`;brushCursor.style.top=`${brushPointer.clientY-viewport.top}px`;
 brushCursor.classList.toggle('removing',Number($('#paint-operation').value)*(brushPointer.shiftKey?-1:1)<0);brushCursor.hidden=false;
}

function captureWeights(){return asset.children.map(m=>({indices:Array.from(m.geometry.attributes.skinIndex.array),weights:Array.from(m.geometry.attributes.skinWeight.array)}));}
function installWeights(data){
 if(!Array.isArray(data)||data.length!==asset.children.length)throw new Error('Pesos salvos incompatíveis com a malha.');
 data.forEach((d,i)=>{const n=asset.children[i].geometry.attributes.position.count*4;if(!Array.isArray(d.indices)||!Array.isArray(d.weights)||d.indices.length!==n||d.weights.length!==n||!d.indices.every(v=>Number.isInteger(v)&&v>=0&&v<19)||!d.weights.every(v=>Number.isFinite(v)&&v>=0&&v<=1))throw new Error('Pesos inválidos.');for(let j=0;j<n;j+=4)if(Math.abs(d.weights.slice(j,j+4).reduce((a,b)=>a+b,0)-1)>.001)throw new Error('Pesos não normalizados.');});
 const meshes=model.children.filter(m=>m.isSkinnedMesh);
 data.forEach((d,i)=>{for(const g of [asset.children[i].geometry,meshes[i].geometry]){g.setAttribute('skinIndex',new THREE.Uint16BufferAttribute(d.indices,4));g.setAttribute('skinWeight',new THREE.Float32BufferAttribute(d.weights,4));}meshes[i].geometry.boundingSphere=null;meshes[i].boundingSphere=null;});updateWeightView();
}
function paintAt(e,dose=1){
 const hit=brushHit(e);if(!hit)return;
 const radius=brushRadius(),strength=THREE.MathUtils.clamp(Number($('#paint-strength').value)||20,1,100)/100;
 const mesh=hit.object,meshIndex=model.children.filter(m=>m.isSkinnedMesh).indexOf(mesh),g=mesh.geometry,si=g.attributes.skinIndex,sw=g.attributes.skinWeight,pos=new THREE.Vector3();let changed=0;
 if(!stroke.saved){paintUndo.push(captureWeights());if(paintUndo.length>8)paintUndo.shift();stroke.saved=true;}
 // Evaluate distances before mutating so this dab uses one consistent posed surface.
 const vertices=[];for(let i=0;i<sw.count;i++){mesh.getVertexPosition(i,pos);mesh.localToWorld(pos);const distance=pos.distanceTo(hit.point);if(distance<radius&&Math.abs(pos.clone().sub(hit.point).dot(raycaster.ray.direction))<radius*.35)vertices.push([i,distance]);}
 for(const [i,distance] of vertices){const key=meshIndex+':'+i;const falloff=1-THREE.MathUtils.smoothstep(distance/radius,0,1),amount=strength*falloff*dose*Number($('#paint-operation').value)*(e.shiftKey?-1:1);const before=[0,1,2,3].reduce((n,j)=>n+(si.getComponent(i,j)===state.selected?sw.getComponent(i,j):0),0);if((amount<0&&before<=0)||(amount>0&&before>=1))continue;const painted=paintInfluences([0,1,2,3].map(j=>si.getComponent(i,j)),[0,1,2,3].map(j=>sw.getComponent(i,j)),state.selected,amount,Math.max(0,JOINTS[state.selected][2]));for(let j=0;j<4;j++){si.setComponent(i,j,painted.indices[j]);sw.setComponent(i,j,painted.weights[j]);}stroke.touched.add(key);changed++;}
 if(changed){si.needsUpdate=true;sw.needsUpdate=true;asset.children[meshIndex].geometry.setAttribute('skinIndex',si.clone());asset.children[meshIndex].geometry.setAttribute('skinWeight',sw.clone());mesh.boundingSphere=null;const view=weightViews.get(mesh);if(view)view.weights=null;updateWeightView();stroke.count=stroke.touched.size;$('#paint-feedback').textContent=`${stroke.count} vértices pintados · ${JOINTS[state.selected][1]}`;revision++;}
}
renderer.domElement.addEventListener('pointerdown',e=>{if(!state.painting||state.busy||e.button!==0)return;e.stopImmediatePropagation();e.preventDefault();state.playing=false;orbit.enabled=false;brushPointer={clientX:e.clientX,clientY:e.clientY,shiftKey:e.shiftKey};stroke={saved:false,touched:new Set(),count:0,last:performance.now()};renderer.domElement.setPointerCapture(e.pointerId);paintAt(e);},{capture:true});
renderer.domElement.addEventListener('pointermove',e=>{brushPointer={clientX:e.clientX,clientY:e.clientY,shiftKey:e.shiftKey};if(stroke)e.stopImmediatePropagation();updateBrushCursor();},{capture:true});
renderer.domElement.addEventListener('pointerleave',()=>{if(!stroke){brushPointer=null;brushCursor.hidden=true;}});
window.addEventListener('blur',()=>{stroke=null;brushPointer=null;orbit.enabled=!gizmo.dragging;brushCursor.hidden=true;});
function finishPaint(e){if(!stroke)return;e.stopImmediatePropagation();stroke=null;orbit.enabled=!gizmo.dragging;if(renderer.domElement.hasPointerCapture(e.pointerId))renderer.domElement.releasePointerCapture(e.pointerId);}
renderer.domElement.addEventListener('pointerup',finishPaint,{capture:true});renderer.domElement.addEventListener('pointercancel',finishPaint,{capture:true});
$('#paint-toggle').onclick=()=>{state.painting=!state.painting;state.playing=false;if(state.painting)state.showWeights=true;updateUI();};
$('#paint-undo').onclick=()=>{if(paintUndo.length)installWeights(paintUndo.pop());$('#paint-feedback').textContent='Pincelada desfeita.';};

const weightViews=new Map();
const weightPalette=['#142d70','#00b8e0','#35ce69','#ffe34b','#f23832'].map(c=>new THREE.Color(c));
function clearWeightView(){
 for(const [mesh,view] of weightViews){mesh.material=view.material;if(view.color)mesh.geometry.setAttribute('color',view.color);else mesh.geometry.deleteAttribute('color');view.preview.dispose();materials(mesh).forEach(m=>m.wireframe=state.wire);}
 weightViews.clear();
}
function updateWeightView(){
 if(state.stage!=='animate')state.painting=false;
 orbit.mouseButtons.RIGHT=state.painting?THREE.MOUSE.ROTATE:THREE.MOUSE.PAN;renderer.domElement.style.cursor=state.painting?'crosshair':'';if(!state.painting){stroke=null;brushCursor.hidden=true;orbit.enabled=!gizmo.dragging;}
 $('#paint-options').classList.toggle('hidden',!state.painting);$('#paint-toggle').setAttribute('aria-pressed',String(state.painting));$('#paint-toggle').classList.toggle('active',state.painting);$('#paint-undo').disabled=!paintUndo.length||state.busy;

 const active=state.showWeights&&state.rigged&&state.stage==='animate';
 $('#weights-toggle').disabled=!state.rigged||state.stage!=='animate'||state.busy;
 $('#weights-toggle').classList.toggle('active',active);$('#weights-toggle').setAttribute('aria-pressed',String(active));
 $('#weight-legend').classList.toggle('hidden',!active);$('#weight-joint').textContent=`Influência · ${JOINTS[state.selected][1]}`;
 if(!active){clearWeightView();return;}
 for(const mesh of model.children.filter(m=>m.isSkinnedMesh)){
  const geometry=mesh.geometry,indices=geometry.getAttribute('skinIndex'),weights=geometry.getAttribute('skinWeight');
  let view=weightViews.get(mesh);
  if(!view){view={material:mesh.material,color:geometry.getAttribute('color'),preview:new THREE.MeshBasicMaterial({vertexColors:true,side:THREE.DoubleSide,toneMapped:false})};weightViews.set(mesh,view);}
  mesh.material=view.preview;view.preview.wireframe=state.wire;
  if(view.joint===state.selected&&view.weights===weights)continue;
  const colors=new Float32Array(weights.count*3),color=new THREE.Color();
  for(let i=0;i<weights.count;i++){
   let weight=0;for(let j=0;j<weights.itemSize;j++)if(indices.getComponent(i,j)===state.selected)weight+=weights.getComponent(i,j);
   const t=THREE.MathUtils.clamp(weight,0,1)*4,stop=Math.min(3,Math.floor(t));color.copy(weightPalette[stop]).lerp(weightPalette[stop+1],t-stop);color.toArray(colors,i*3);
  }
  geometry.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));view.joint=state.selected;view.weights=weights;
 }
}
function updateVisual(){
 updateWeightView();
 rigVisual.visible=state.showSkeleton&&state.stage!=='import';const pts=[];
 spheres.forEach((s,i)=>{if(state.rigged&&state.stage==='animate')skeleton.bones[i].getWorldPosition(s.position);else s.position.copy(state.markers[i]);s.scale.setScalar(i===state.selected?1.5:1);s.material.color.set(i===state.selected?'#e2ff85':'#b7d49b');});
 JOINTS.forEach((j,i)=>{if(j[2]>=0)pts.push(...spheres[j[2]].position.toArray(),...spheres[i].position.toArray());});
 lines.geometry.dispose();lines.geometry=new THREE.BufferGeometry();lines.geometry.setAttribute('position',new THREE.Float32BufferAttribute(pts,3));
}
function selectJoint(index){state.selected=Number(index);$('#joint-select').value=String(state.selected);updateGizmo();updateVisual();updateFields();$$('.joint-row').forEach(b=>b.classList.toggle('active',Number(b.dataset.joint)===state.selected));}
function updateGizmo(){
 gizmo.detach();if(state.painting||state.busy||state.playing||state.stage==='import'||!state.showSkeleton)return;
 if(state.stage==='rig'){gizmo.setMode('translate');gizmo.setSpace('world');gizmo.attach(spheres[state.selected]);}
 else if(state.rigged){const b=skeleton.bones[state.selected];if(state.tool==='rotate'){gizmo.setMode('rotate');gizmo.setSpace('local');gizmo.attach(b);}else{gizmo.setMode('translate');gizmo.setSpace('world');b.getWorldPosition(ikTarget.position);gizmo.attach(ikTarget);}}
}
function updateFields(){
 const rotating=state.stage==='animate'&&state.tool==='rotate';let v;
 if(state.stage==='rig')v=state.markers[state.selected];else if(state.rigged)v=rotating?skeleton.bones[state.selected].rotation:skeleton.bones[state.selected].getWorldPosition(new THREE.Vector3());else v=state.markers[state.selected];
 for(const a of ['x','y','z']){const input=$(`#axis-${a}`);if(document.activeElement!==input)input.value=(v[a]*(rotating?180/Math.PI:1)).toFixed(rotating?1:3);input.step=rotating?'1':'.01';input.disabled=state.busy||state.stage==='import';}
 $('#transform-label').textContent=rotating?'Rotação · graus':'Posição · metros';$('#transform-space').textContent=rotating?'Local':'Global';
 $('#joint-help').textContent=state.stage==='animate'&&state.tool==='move'?(IK_CHAINS[JOINTS[state.selected][0]]?'Mão ou pé: o membro acompanha por IK.':([12,16].includes(state.selected)?'Joelho: coxa e canela se ajustam; a cintura acompanha e os pés tentam manter o apoio.':[6,9].includes(state.selected)?'Cotovelo: braço, antebraço e tronco acompanham, preservando o alcance.':state.selected===0?'Quadril: movimenta o corpo inteiro.':'O antecessor gira para acompanhar o alvo; os descendentes seguem sem esticar os ossos.')):'Arraste o controle no personagem ou ajuste os valores.';
}
function renderTimeline(){
 $('#ruler').innerHTML=Array.from({length:11},(_,i)=>`<span style="left:${i*9.8+.8}%">${(state.duration*i/10).toFixed(1)}</span>`).join('');
 $('#key-track').replaceChildren();state.keys.sort((a,b)=>a.time-b.time).forEach(k=>{const b=document.createElement('button');b.className=`key${Math.abs(k.time-state.time)<.02?' selected':''}`;b.style.left=`${timePercent(k.time)}%`;b.title=`Pose em ${k.time.toFixed(2)} s · arraste para mover`;b.setAttribute('aria-label',`Keyframe ${k.time.toFixed(2)} segundos`);b.addEventListener('pointerdown',e=>dragKey(e,k));$('#key-track').append(b);});
 $('#key-count').textContent=`${state.keys.length} poses`;$('#clip-label').textContent=state.keys.length?'ACTION_01':'SEM CLIPE';updateTimeUI();
}
function timePercent(t){return .8+98*t/state.duration;}
function updateTimeUI(){$('#playhead').style.left=`${timePercent(state.time)}%`;$('#time-readout').textContent=`${state.time.toFixed(2)} / ${state.duration.toFixed(2)} s`;}
function rigNeedsRebuild(){return state.rigged&&bindMarkers&&state.markers.some((p,i)=>p.toArray().some((v,a)=>Math.abs(v-bindMarkers[i][a])>1e-7));}
function updateUI(){
 $('#asset-name').textContent=state.name;$('#project-title').textContent=state.name;
 const vertices=asset?.children.reduce((n,m)=>n+m.geometry.attributes.position.count,0)||0;
 $('#asset-meta').textContent=state.rigged?'Rig ativo · 19 juntas':sourceKind==='demo'?'Malha de demonstração':'GLB importado · sem rig';$('#stats').textContent=`${vertices.toLocaleString('pt-BR')} vértices · ${state.rigged?'19 juntas · 4 influências':'malha estática'}`;
 $$('[data-stage]').forEach(b=>{b.classList.toggle('active',b.dataset.stage===state.stage);b.disabled=state.busy||(b.dataset.stage==='animate'&&(!state.rigged||rigNeedsRebuild()));});
 $('#import-panel').classList.toggle('hidden',state.stage!=='import');$('#rig-panel').classList.toggle('hidden',state.stage!=='rig');$('#pose-panel').classList.toggle('hidden',state.stage!=='animate');
 const titles={import:['01 / PREPARAÇÃO','Tudo começa aqui.','Prepare seu personagem para ganhar vida.','MODELO ORIGINAL'],rig:['02 / RIGGING ASSISTIDO','Dê estrutura à ideia.','Um esqueleto simples. Infinitas poses.','AJUSTE DO ESQUELETO'],animate:['03 / ANIMAÇÃO','Encontre o movimento.','Uma pose de cada vez.','EDIÇÃO DE ANIMAÇÃO']};const t=titles[state.stage];$('#inspector-kicker').textContent=t[0];$('#inspector-title').textContent=t[1];$('#inspector-description').textContent=t[2];$('#view-state').textContent=t[3];
 $('#hint').classList.toggle('hidden',state.stage==='animate');
 $('#hint').textContent=state.stage==='rig'?'Ajuste as articulações e gere o rig para começar':state.stage==='import'?'GLB em pose A ou T · corpo inteiro · até 200 mil vértices':'';
 $('#export').disabled=state.busy||!state.rigged||state.stage!=='animate';$('#save-project').disabled=state.busy;
 for(const id of ['play','rewind','add-key','copy-key','paste-key','delete-key'])$(`#${id}`).disabled=state.busy||state.stage!=='animate'||(id==='play'&&!state.keys.length)||(id==='paste-key'&&!clipboard)||(id==='delete-key'&&!state.keys.some(k=>Math.abs(k.time-state.time)<.02));
 $('#undo').disabled=!history.length||state.busy;$('#redo').disabled=!future.length||state.busy;
 $('#tool-rotate').classList.toggle('active',state.stage==='animate'&&state.tool==='rotate');$('#tool-move').classList.toggle('active',state.stage==='rig'||state.tool==='move');$('#fk-mode').classList.toggle('active',state.tool==='rotate');$('#ik-mode').classList.toggle('active',state.tool==='move');$('#tool-rotate').disabled=state.stage!=='animate'||state.busy;
 $('#play').innerHTML=icon(state.playing?'pause':'play');$('#play').setAttribute('aria-label',state.playing?'Pausar':'Reproduzir');
 $('#tree').innerHTML=JOINTS.map((j,i)=>{let depth=0,p=j[2];while(p>=0){depth++;p=JOINTS[p][2];}return `<button class="joint-row${i===state.selected?' active':''}" data-joint="${i}" style="padding-left:${10+Math.min(depth,3)*10}px"><span class="joint-dot"></span>${j[1]}</button>`;}).join('');
 $$('[data-joint]').forEach(b=>b.onclick=()=>selectJoint(b.dataset.joint));$('#joint-select').value=state.selected;createIcons({icons});updateVisual();updateGizmo();updateFields();renderTimeline();
}
function snapshot(){return {bindMarkers:structuredClone(bindMarkers),markers:state.markers.map(p=>p.toArray()),pose:skeleton?capturePose(skeleton):null,keys:structuredClone(state.keys),time:state.time,duration:state.duration,stage:state.stage,rigged:state.rigged};}
function record(){history.push(snapshot());if(history.length>40)history.shift();future=[];$('#undo').disabled=false;$('#redo').disabled=true;revision++;}
function restore(s){state.playing=false;state.markers=s.markers.map(p=>new THREE.Vector3(...p));state.keys=s.keys;state.time=s.time;state.duration=s.duration;state.stage=s.stage;$('#duration').value=s.duration;if(s.rigged!==state.rigged)replaceModel(s.rigged);if(s.pose&&skeleton)applyPose(skeleton,s.pose);updateUI();}
function undo(){if(!history.length||state.busy)return;future.push(snapshot());restore(history.pop());revision++;}
function redo(){if(!future.length||state.busy)return;history.push(snapshot());restore(future.pop());revision++;}
function setStage(stage){if(state.busy)return;if(stage==='animate'&&(!state.rigged||rigNeedsRebuild()))return;state.playing=false;if(state.rigged&&stage!=='animate')applyPose(skeleton,bindPose);state.stage=stage;if(stage==='animate')seek(state.time);updateUI();}
function frameCamera(front=false){orbit.target.set(0,1,0);camera.position.set(front?0:2.2,front?1.02:1.7,front?4.6:4.6);orbit.update();$('#view-name').textContent=front?'Frontal':'Perspectiva';}
function applyMarkerMove(point){state.markers[state.selected].copy(point);if($('#mirror').checked){const name=JOINTS[state.selected][0],other=name.endsWith('L')?name.slice(0,-1)+'R':name.endsWith('R')?name.slice(0,-1)+'L':null;const idx=JOINTS.findIndex(j=>j[0]===other);if(idx>=0)state.markers[idx].set(-point.x,point.y,point.z);}updateVisual();updateFields();$$('[data-stage=animate]').forEach(b=>b.disabled=!!rigNeedsRebuild());$('#hint').textContent=rigNeedsRebuild()?'Esqueleto alterado · gere o rig novamente para aplicar':'Ajuste as articulações e gere o rig para começar';}
let moveStartPose=null;
function moveIK(point){if(moveStartPose)applyPose(skeleton,moveStartPose);moveBoneWorld(skeleton,state.selected,point);updateVisual();updateFields();}
gizmo.addEventListener('dragging-changed',e=>{orbit.enabled=!e.value&&!stroke;});gizmo.addEventListener('mouseDown',()=>{state.playing=false;record();moveStartPose=state.stage==='animate'&&state.tool==='move'?capturePose(skeleton):null;});gizmo.addEventListener('mouseUp',()=>{moveStartPose=null;updateGizmo();updateFields();});
gizmo.addEventListener('objectChange',()=>{if(state.stage==='rig')applyMarkerMove(spheres[state.selected].position.clone());else if(state.tool==='move')moveIK(ikTarget.position);else {updateVisual();updateFields();}});
let clickStart;
renderer.domElement.addEventListener('pointerdown',e=>{clickStart=[e.clientX,e.clientY];});
renderer.domElement.addEventListener('pointerup',e=>{if(state.painting||state.busy||gizmo.dragging||gizmo.axis||!clickStart||Math.hypot(e.clientX-clickStart[0],e.clientY-clickStart[1])>5||!rigVisual.visible)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(spheres)[0];if(hit)selectJoint(hit.object.userData.index);});
function weightGeometry(geometry,points=state.markers){return new Promise((resolve,reject)=>{const worker=new Worker(new URL('./weights.worker.js',import.meta.url),{type:'module'});const timeout=setTimeout(()=>{worker.terminate();reject(new Error('O cálculo excedeu 60 segundos. Tente uma malha menor.'));},60000);worker.onmessage=({data})=>{clearTimeout(timeout);worker.terminate();if(data.error)reject(new Error(data.error));else resolve(data);};worker.onerror=e=>{clearTimeout(timeout);worker.terminate();reject(new Error(e.message));};const attr=geometry.attributes.position,positions=new Float32Array(attr.count*3);for(let i=0;i<attr.count;i++){positions[i*3]=attr.getX(i);positions[i*3+1]=attr.getY(i);positions[i*3+2]=attr.getZ(i);}worker.postMessage({positions,segments:segmentsFor(points)},[positions.buffer]);});}
async function refineWeights(){
 if(!state.rigged||state.busy)return;
 state.playing=false;busy(true,'Refinando a transição dos ombros…');
 try{
  const points=bindMarkers.map(v=>new THREE.Vector3(...v)),computed=[];
  for(const mesh of asset.children)computed.push(await weightGeometry(mesh.geometry,points));
  const meshes=model.children.filter(m=>m.isSkinnedMesh);
  if(meshes.length!==asset.children.length)throw new Error('A malha do rig não corresponde ao modelo original.');
  asset.children.forEach((mesh,i)=>{
   for(const geometry of [mesh.geometry,meshes[i].geometry]){
    geometry.setAttribute('skinIndex',new THREE.Uint16BufferAttribute(computed[i].indices,4));
    geometry.setAttribute('skinWeight',new THREE.Float32BufferAttribute(computed[i].weights,4));
   }
  });
  paintUndo.length=0;revision++;toast('Pesos recalculados. Esqueleto, pose e animação preservados.');
 }catch(e){toast(e.message,true);}finally{busy(false);}
}
async function generateRig(){
 if(state.busy)return;busy(true);state.playing=false;gizmo.detach();
 try{const computed=[];for(const mesh of asset.children)computed.push(await weightGeometry(mesh.geometry));asset.children.forEach((mesh,i)=>{mesh.geometry.setAttribute('skinIndex',new THREE.Uint16BufferAttribute(computed[i].indices,4));mesh.geometry.setAttribute('skinWeight',new THREE.Float32BufferAttribute(computed[i].weights,4));});replaceModel(true);state.stage='animate';state.tool='rotate';state.keys=[];state.time=0;history=[];future=[];revision++;toast('Rig criado. Selecione uma articulação para posar o personagem.');}
 catch(e){toast(e.message,true);}finally{busy(false);}
}
function seek(t){state.time=THREE.MathUtils.clamp(Math.round(t*30)/30,0,state.duration);const p=samplePose(state.keys,state.time);if(p&&state.rigged&&state.stage==='animate')applyPose(skeleton,p);updateVisual();updateGizmo();updateFields();renderTimeline();$('#delete-key').disabled=!state.keys.some(k=>Math.abs(k.time-state.time)<.02)||state.stage!=='animate';}
function addKey(){if(!state.rigged||state.stage!=='animate'||state.busy)return;state.playing=false;record();const pose=capturePose(skeleton);state.keys=state.keys.filter(k=>Math.abs(k.time-state.time)>.02);state.keys.push({time:state.time,pose});updateUI();toast(`Pose salva em ${state.time.toFixed(2)} s`);}
function togglePlay(){if(state.stage!=='animate'||!state.keys.length)return;state.playing=!state.playing;if(state.playing&&state.time>=state.duration)state.time=0;updateUI();}
function scrub(e){if(e.target.closest('.key')||state.stage!=='animate')return;state.playing=false;const r=$('#timeline-grid').getBoundingClientRect();seek(((e.clientX-r.left)/r.width*100-.8)/98*state.duration);updateUI();}
$('#ruler').addEventListener('pointerdown',scrub);$('#key-track').addEventListener('pointerdown',scrub);
function dragKey(e,k){e.stopPropagation();if(state.stage!=='animate')return;state.playing=false;record();const r=$('#timeline-grid').getBoundingClientRect();const move=event=>{k.time=THREE.MathUtils.clamp(Math.round((((event.clientX-r.left)/r.width*100-.8)/98*state.duration)*30)/30,0,state.duration);state.time=k.time;applyPose(skeleton,k.pose);updateVisual();renderTimeline();};const end=()=>{state.keys=state.keys.filter(v=>v===k||Math.abs(v.time-k.time)>.02);window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',end);updateUI();};state.time=k.time;applyPose(skeleton,k.pose);window.addEventListener('pointermove',move);window.addEventListener('pointerup',end);updateVisual();renderTimeline();}
function makeWalk(){if(!state.rigged||state.stage!=='animate'||state.busy)return;try{const result=generateWalk(bindMarkers.map(p=>new THREE.Vector3(...p)),{speed:$('#walk-speed').value,stride:$('#walk-stride').value});record();state.playing=false;state.keys=result.keys;state.duration=result.duration;$('#duration').value=state.duration;state.loop=true;$('#loop').classList.add('active');state.selected=0;state.tool='rotate';seek(0);updateUI();toast('Caminhada criada. Pressione Espaço para reproduzir; as poses são editáveis.');}catch(e){toast(e.message,true);}}
function makeMotion(kind){if(!state.rigged||state.stage!=='animate'||state.busy)return;try{const generate=kind==='idle'?generateIdle:generateRun;const result=generate(bindMarkers.map(p=>new THREE.Vector3(...p)),{speed:$('#motion-speed').value,intensity:$('#motion-intensity').value});record();state.playing=false;state.keys=result.keys;state.duration=result.duration;$('#duration').value=state.duration;state.loop=true;$('#loop').classList.add('active');state.selected=0;state.tool='rotate';seek(0);updateUI();toast(`${result.name} criado. Pressione Espaço para reproduzir.`);}catch(e){toast(e.message,true);}}
function makeWave(){if(!state.rigged)return;record();state.playing=false;state.keys=[];const poses=[0,.25,.5,.75,1];for(const t of poses){applyPose(skeleton,bindPose);const b=skeleton.bones;b[8].rotation.z=-.9;b[9].rotation.z=-1.5;b[10].rotation.z=t===0||t===1?0:Math.sin(t*Math.PI*6)*.5;b[4].rotation.z=.08;state.keys.push({time:t*state.duration,pose:capturePose(skeleton)});}seek(0);state.selected=10;state.tool='rotate';updateUI();toast('Aceno criado com 5 poses. Pressione Espaço para reproduzir.');}
function download(data,filename,type){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
async function exportGLB(){if(!state.rigged||state.busy)return;state.playing=false;busy(true,'Preparando GLB com rig e animação…');const pose=capturePose(skeleton);try{clearWeightView();applyPose(skeleton,bindPose);const clip=makeClip(state.keys,state.duration);const buffer=await new GLTFExporter().parseAsync(model,{binary:true,animations:clip?[clip]:[],onlyVisible:true});download(buffer,'riglab-personagem.glb','model/gltf-binary');toast('GLB exportado com esqueleto'+(clip?' e animação.':'.'));}catch(e){toast('Falha ao exportar: '+e.message,true);}finally{applyPose(skeleton,pose);busy(false);updateWeightView();}}
const toBase64=buffer=>{let s='';const bytes=new Uint8Array(buffer);for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s);};
async function saveProject(){if(state.busy)return;state.playing=false;busy(true,'Salvando projeto…');try{const glb=await new GLTFExporter().parseAsync(asset,{binary:true});const data={format:'riglab',version:1,name:state.name,sourceKind,asset:toBase64(glb),weights:state.rigged?captureWeights():undefined,state:snapshot()};download(JSON.stringify(data),'personagem.riglab','application/json');$('#status').textContent='● Projeto salvo';toast('Projeto salvo. Use Abrir projeto para continuar depois.');}catch(e){toast(e.message,true);}finally{busy(false);}}
function loader(){const manager=new THREE.LoadingManager();manager.setURLModifier(url=>{if(url.startsWith('blob:')||url.startsWith('data:'))return url;throw new Error('Use um GLB autocontido, com texturas e geometria incorporadas.');});return new GLTFLoader(manager);}
async function importFile(file){if(!file||state.busy)return;if(!file.name.toLowerCase().endsWith('.glb'))return toast('Selecione um arquivo .glb. Imagens são apenas referências.',true);if(file.size>30*1024*1024)return toast('Limite do protótipo: arquivo GLB de até 30 MB.',true);busy(true,'Importando modelo…');try{const gltf=await loader().parseAsync(await file.arrayBuffer(),'');const normalized=normalize(gltf.scene);loadAsset(normalized,file.name.replace(/\.glb$/i,''));toast('Modelo importado. Confira a orientação antes de ajustar o rig.');}catch(e){toast('Não foi possível importar: '+e.message,true);}finally{busy(false);$('#model-file').value='';}}
function validateProject(p){if(p?.format!=='riglab'||p.version!==1||typeof p.asset!=='string'||typeof p.name!=='string')throw new Error('Formato de projeto inválido.');const s=p.state;const vec=(v,n)=>Array.isArray(v)&&v.length===n&&v.every(x=>typeof x==='number'&&Number.isFinite(x)&&Math.abs(x)<1000);const pose=p=>Array.isArray(p)&&p.length===JOINTS.length&&p.every(v=>vec(v.p,3)&&vec(v.q,4)&&Math.hypot(...v.q)>.5&&Math.hypot(...v.q)<1.5);if(!s||!Array.isArray(s.markers)||s.markers.length!==19||!s.markers.every(v=>vec(v,3))||!Number.isFinite(s.duration)||s.duration<.4||s.duration>30||!Number.isFinite(s.time)||s.time<0||s.time>s.duration||!['import','rig','animate'].includes(s.stage)||typeof s.rigged!=='boolean'||(s.stage==='animate'&&!s.rigged)||!Array.isArray(s.keys)||s.keys.length>1000||!s.keys.every(k=>Number.isFinite(k.time)&&k.time>=0&&k.time<=s.duration&&pose(k.pose))||(s.rigged&&(!pose(s.pose)||!Array.isArray(s.bindMarkers)||s.bindMarkers.length!==19||!s.bindMarkers.every(v=>vec(v,3)))))throw new Error('O projeto contém dados de rig ou animação inválidos.');}
async function openProject(file){if(!file||state.busy)return;if(file.size>80*1024*1024)return toast('Projeto maior que o limite de 80 MB.',true);busy(true,'Abrindo projeto…');try{const p=JSON.parse(await file.text());validateProject(p);const bytes=Uint8Array.from(atob(p.asset),c=>c.charCodeAt(0));const gltf=await loader().parseAsync(bytes.buffer,'');const normalized=normalize(gltf.scene);loadAsset(normalized,p.name,p.sourceKind==='demo'?'demo':'import');state.markers=p.state.markers.map(v=>new THREE.Vector3(...v));if(p.state.rigged){state.markers=p.state.bindMarkers.map(v=>new THREE.Vector3(...v));const computed=[];for(const mesh of asset.children)computed.push(await weightGeometry(mesh.geometry));asset.children.forEach((m,i)=>{m.geometry.setAttribute('skinIndex',new THREE.Uint16BufferAttribute(computed[i].indices,4));m.geometry.setAttribute('skinWeight',new THREE.Float32BufferAttribute(computed[i].weights,4));});replaceModel(true);if(p.weights)installWeights(p.weights);}restore(p.state);history=[];future=[];toast('Projeto restaurado com modelo, rig e poses.');}catch(e){toast('Não foi possível abrir: '+e.message,true);}finally{busy(false);$('#project-file').value='';}}

$('#auto-rig').onclick=generateRig;$('#refine-weights').onclick=refineWeights;$('#import').onclick=()=>$('#model-file').click();$('#model-file').onchange=e=>importFile(e.target.files[0]);$('#demo').onclick=()=>{if(!state.busy)loadAsset(normalize(createDemo()),'Sentinela da floresta','demo');};$('#open-project').onclick=()=>$('#project-file').click();$('#project-file').onchange=e=>openProject(e.target.files[0]);$('#save-project').onclick=saveProject;$('#export').onclick=exportGLB;
$$('[data-stage]').forEach(b=>b.onclick=()=>setStage(b.dataset.stage));$('#start-rig').onclick=()=>setStage('rig');$('#edit-rig').onclick=()=>{setStage('rig');toast('Ao gerar novamente, o rig e o clipe serão substituídos.');};
$('#joint-select').onchange=e=>selectJoint(e.target.value);$('#frame-camera').onclick=()=>frameCamera();$('#front-camera').onclick=()=>frameCamera(true);
function setTool(tool){if(state.stage==='import')return;state.tool=tool;updateUI();}
$('#tool-rotate').onclick=()=>setTool('rotate');$('#tool-move').onclick=()=>setTool('move');$('#fk-mode').onclick=()=>setTool('rotate');$('#ik-mode').onclick=()=>setTool('move');
$('#weights-toggle').onclick=()=>{state.showWeights=!state.showWeights;if(!state.showWeights)state.painting=false;updateWeightView();updateGizmo();};
$('#skeleton-toggle').onclick=()=>{state.showSkeleton=!state.showSkeleton;$('#skeleton-toggle').classList.toggle('active',state.showSkeleton);updateVisual();updateGizmo();};$('#wire-toggle').onclick=()=>{state.wire=!state.wire;$('#wire-toggle').classList.toggle('active',state.wire);model.traverse(m=>{if(m.isMesh)materials(m).forEach(v=>v.wireframe=state.wire);});};$('#grid-toggle').onclick=()=>{grid.visible=!grid.visible;ring.visible=grid.visible;$('#grid-toggle').classList.toggle('active',grid.visible);};
for(const axis of ['x','y','z'])$(`#axis-${axis}`).onchange=e=>{const n=Number(e.target.value);if(!Number.isFinite(n)||Math.abs(n)>100)return updateFields();record();state.playing=false;if(state.stage==='rig'){const v=state.markers[state.selected].clone();v[axis]=n;applyMarkerMove(v);}else if(state.rigged&&state.tool==='rotate'){skeleton.bones[state.selected].rotation[axis]=THREE.MathUtils.degToRad(n);skeleton.bones[0].updateMatrixWorld(true);}else if(state.rigged){const v=skeleton.bones[state.selected].getWorldPosition(new THREE.Vector3());v[axis]=n;moveIK(v);}updateVisual();updateGizmo();updateFields();};
function resetMarkers(){record();state.markers=defaultMarkers(2,$('#rest-type').value,THREE.MathUtils.clamp(Number($('#rig-width').value)||1,.5,1.5));updateUI();}$('#rest-type').onchange=resetMarkers;$('#rig-width').onchange=resetMarkers;
function rotateAsset(axis){if(state.busy)return;asset.rotation[axis]+=Math.PI/2;const next=normalize(asset);loadAsset(next,state.name,sourceKind);state.stage='import';updateUI();}$('#turn-model').onclick=()=>rotateAsset('y');$('#upright-model').onclick=()=>rotateAsset('x');
$('#undo').onclick=undo;$('#redo').onclick=redo;$('#neutral').onclick=()=>{record();state.playing=false;applyPose(skeleton,bindPose);updateUI();};$('#wave').onclick=makeWave;$('#walk').onclick=makeWalk;$('#idle').onclick=()=>makeMotion('idle');$('#run').onclick=()=>makeMotion('run');$('#add-key').onclick=addKey;$('#play').onclick=togglePlay;$('#rewind').onclick=()=>{state.playing=false;seek(0);updateUI();};$('#loop').onclick=()=>{state.loop=!state.loop;$('#loop').classList.toggle('active',state.loop);};
$('#copy-key').onclick=()=>{clipboard=capturePose(skeleton);updateUI();toast('Pose copiada. Escolha o tempo e cole.');};$('#paste-key').onclick=()=>{if(!clipboard)return;record();state.playing=false;applyPose(skeleton,clipboard);state.keys=state.keys.filter(k=>Math.abs(k.time-state.time)>.02);state.keys.push({time:state.time,pose:structuredClone(clipboard)});updateUI();};$('#delete-key').onclick=()=>{record();state.keys=state.keys.filter(k=>Math.abs(k.time-state.time)>.02);updateUI();};
$('#duration').onchange=e=>{const next=THREE.MathUtils.clamp(Number(e.target.value)||3,.4,30);record();state.playing=false;const factor=next/state.duration;state.keys.forEach(k=>k.time=k.time*factor);state.time*=factor;state.duration=next;e.target.value=next;updateUI();};
$$('[data-reference]').forEach(b=>b.onclick=()=>{const [file,name]=refs[b.dataset.reference];$('#reference-title').textContent=name;$('#reference-image').src=`${import.meta.env.BASE_URL}references/${file}.jpg`;$('#reference-image').alt=name;$('#reference-dialog').showModal();});$('#close-reference').onclick=()=>$('#reference-dialog').close();
viewport.addEventListener('dragover',e=>e.preventDefault());viewport.addEventListener('drop',e=>{e.preventDefault();importFile(e.dataTransfer.files[0]);});
window.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(document.activeElement.tagName)||$('#reference-dialog').open||state.busy)return;const key=e.key.toLowerCase();if((e.ctrlKey||e.metaKey)&&key==='z'){e.preventDefault();e.shiftKey?redo():undo();return;}if(e.code==='Space'){e.preventDefault();togglePlay();}if(key==='k')addKey();if(key==='r'&&state.stage==='animate')setTool('rotate');if(key==='g')setTool('move');if(key==='f')frameCamera();});
const clock=new THREE.Clock();function tick(){requestAnimationFrame(tick);const delta=Math.min(clock.getDelta(),.1);if(state.playing&&state.rigged){state.time+=delta;if(state.time>state.duration){if(state.loop)state.time%=state.duration;else{state.time=state.duration;state.playing=false;updateUI();}}const pose=samplePose(state.keys,state.time);if(pose)applyPose(skeleton,pose);updateVisual();updateTimeUI();}if(!gizmo.dragging&&!stroke)orbit.update();if(state.painting&&brushPointer){const now=performance.now();if(stroke&&now-stroke.last>=33){paintAt(brushPointer,Math.min((now-stroke.last)/1000,.1)*3);stroke.last=now;}updateBrushCursor();}renderer.render(scene,camera);}loadAsset(normalize(createDemo()),'Sentinela da floresta','demo');tick();
// Read-only diagnostics for integration tests and support; no editor internals exposed.
window.riglabDiagnostics=()=>({stage:state.stage,rigged:state.rigged,bones:skeleton?.bones.length||0,keyframes:state.keys.length,time:state.time,name:state.name,vertices:asset.children.reduce((n,m)=>n+m.geometry.attributes.position.count,0),selected:JOINTS[state.selected][0],joint:skeleton?.bones[state.selected].getWorldPosition(new THREE.Vector3()).toArray(),pose:skeleton?capturePose(skeleton):null});
