import * as THREE from 'three';
import {islandPieces,packIslands,islandPath,cropIsland,restoreIsland} from './uv-islands.js';
import {textureEntries,uvLayout,uvSVG} from './uv.js';
export function createTexturesPanel(actions){
 const dialog=document.createElement('dialog');dialog.id='textures-dialog';dialog.innerHTML=`<div class="dialog-heading"><strong>Texturas e UV</strong><button id="close-textures" aria-label="Fechar texturas">✕</button></div><div class="texture-workspace"><div class="texture-view"><div class="texture-toolbar"><button id="texture-zoom-out" aria-label="Diminuir zoom">−</button><output id="texture-zoom">100%</output><button id="texture-zoom-in" aria-label="Aumentar zoom">+</button><button id="texture-fit">Ajustar</button><button id="texture-actual">100%</button><button id="texture-tools" aria-expanded="true">Ferramentas</button></div><div class="texture-preview"><canvas id="texture-preview" aria-label="Prévia da textura e mapa UV"></canvas></div><small class="muted">Scroll para ampliar · Arraste para navegar · Clique em uma ilha para isolar</small></div><div class="texture-controls"><label>Material e mapa<select id="texture-entry" aria-label="Material e mapa"></select></label><label>Visualização<select id="texture-mode"><option value="atlas">Mapa original</option><option value="islands">Ilhas separadas</option></select></label><label id="island-picker" hidden>Ilha<select id="texture-island" aria-label="Ilha UV"></select></label><button id="download-island" hidden>Exportar ilha PNG</button><button id="replace-island" hidden>Importar ilha corrigida</button><label class="field-row">Mostrar contornos UV<input id="texture-lines" type="checkbox" checked/></label><p id="texture-info" class="muted"></p><button id="download-texture" class="wide">Exportar textura completa PNG</button><button id="download-uv" class="wide">Exportar UV PNG transparente</button><button id="download-uv-svg" class="wide">Exportar UV SVG</button><button id="replace-texture" class="wide primary">Importar textura completa corrigida</button><button id="restore-texture" class="wide">Restaurar textura original</button><p id="texture-notice" class="muted" role="status"></p><p class="muted">Para editar uma peça, selecione a ilha, exporte seu PNG e importe a correção com as mesmas dimensões. A peça volta à posição original. Edite a textura completa no tamanho original. As linhas UV são uma camada de referência: não as inclua na imagem corrigida. Regiões que compartilham UV recebem a mesma pintura. A substituição vale para o material e mapa selecionados.</p></div></div><input type="file" id="texture-file" accept="image/png,image/jpeg,image/webp" hidden/>`;
 document.body.append(dialog);const $=s=>dialog.querySelector(s);let asset=null,entries=[],originals=new Map(),owned=new Set(),working=false,importPiece=null;
 const key=e=>`${e.meshIndex}:${e.materialIndex}:${e.slot}`,entry=()=>entries[Number($('#texture-entry').value)];
 const viewport=$('.texture-preview'),previewCanvas=$('#texture-preview');let zoom=1,panX=0,panY=0,drag=null,viewPieces=[];
 const fitScale=()=>Math.min(viewport.clientWidth/previewCanvas.width,viewport.clientHeight/previewCanvas.height)||1;
 function positionView(){const scale=fitScale()*zoom,w=previewCanvas.width*scale,h=previewCanvas.height*scale;
  panX=THREE.MathUtils.clamp(panX,-w/2-viewport.clientWidth/2+40,w/2+viewport.clientWidth/2-40);panY=THREE.MathUtils.clamp(panY,-h/2-viewport.clientHeight/2+40,h/2+viewport.clientHeight/2-40);
  previewCanvas.style.width=`${w}px`;previewCanvas.style.height=`${h}px`;previewCanvas.style.transform=`translate(${(viewport.clientWidth-w)/2+panX}px, ${(viewport.clientHeight-h)/2+panY}px)`;
  $('#texture-zoom').textContent=`${Math.round(scale*100)}%`;$('.texture-toolbar').querySelectorAll('button').forEach(b=>b.disabled=working||!entry());
 }
 function fit(){zoom=1;panX=panY=0;positionView();}
 function setZoom(next,x=viewport.clientWidth/2,y=viewport.clientHeight/2){if(working||!entry())return;next=THREE.MathUtils.clamp(next,Math.min(1,1/fitScale()),32);const ratio=next/zoom;panX=(panX+viewport.clientWidth/2-x)*ratio+x-viewport.clientWidth/2;panY=(panY+viewport.clientHeight/2-y)*ratio+y-viewport.clientHeight/2;zoom=next;positionView();}
 $('#texture-zoom-in').onclick=()=>setZoom(zoom*1.4);$('#texture-zoom-out').onclick=()=>setZoom(zoom/1.4);$('#texture-fit').onclick=fit;$('#texture-actual').onclick=()=>setZoom(1/fitScale());
 $('#texture-tools').onclick=()=>{const hidden=$('.texture-workspace').classList.toggle('tools-hidden');$('#texture-tools').setAttribute('aria-expanded',String(!hidden));};
 viewport.addEventListener('wheel',e=>{e.preventDefault();const rect=viewport.getBoundingClientRect();setZoom(zoom*Math.exp(-e.deltaY*(e.deltaMode===1?.03:.002)),e.clientX-rect.left,e.clientY-rect.top);},{passive:false});
 viewport.addEventListener('pointerdown',e=>{if(e.button!==0||working||!entry())return;e.preventDefault();drag={id:e.pointerId,x:e.clientX,y:e.clientY,panX,panY};viewport.setPointerCapture(e.pointerId);viewport.classList.add('dragging');});
 viewport.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;panX=drag.panX+e.clientX-drag.x;panY=drag.panY+e.clientY-drag.y;positionView();});
 const endDrag=e=>{const click=drag&&e.type==='pointerup'&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<4;drag=null;viewport.classList.remove('dragging');if(click&&$('#texture-mode').value==='islands'){const r=previewCanvas.getBoundingClientRect(),x=(e.clientX-r.left)*previewCanvas.width/r.width,y=(e.clientY-r.top)*previewCanvas.height/r.height;const hit=viewPieces.find(p=>p.triangles.some(t=>{const cross=(a,b)=>(b[0]-a[0])*(y-a[1])-(b[1]-a[1])*(x-a[0]),v=[cross(t[0],t[1]),cross(t[1],t[2]),cross(t[2],t[0])];return v.every(n=>n>=0)||v.every(n=>n<=0);}));if(hit){$('#texture-island').value=String(hit.id);render();fit();}}};viewport.addEventListener('pointerup',endDrag);viewport.addEventListener('pointercancel',endDrag);viewport.addEventListener('lostpointercapture',endDrag);
 new ResizeObserver(()=>{if(dialog.open)positionView();}).observe(viewport);
 function canvasFor(e,lines=false,texture=false,preview=false){const image=e.texture.image;let width=image.width,height=image.height;if(!width||!height||width*height>67108864)throw new Error('Textura maior que o limite de 64 megapixels.');if(preview){const scale=Math.min(1,4096/Math.max(width,height));width=Math.round(width*scale);height=Math.round(height*scale);}const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');if(texture)ctx.drawImage(image,0,0,width,height);if(lines){ctx.strokeStyle='#ff4c90';ctx.lineWidth=preview?2:1;ctx.beginPath();for(const edge of uvLayout(e).edges){ctx.moveTo(edge[0][0]*width,edge[0][1]*height);ctx.lineTo(edge[1][0]*width,edge[1][1]*height);}ctx.stroke();}return canvas;}
 function piecesFor(e){return islandPieces(uvLayout(e),e.texture.image.width,e.texture.image.height);}
 function selectedPiece(){return piecesFor(entry()).find(p=>String(p.id)===$('#texture-island').value);}
 function islandCanvas(e,layout){const all=islandPieces(layout,e.texture.image.width,e.texture.image.height),selected=all.find(p=>String(p.id)===$('#texture-island').value),packed=selected?{pieces:[{...selected,displayX:24,displayY:24}],width:selected.width+48,height:selected.height+48}:packIslands(all),scale=Math.min(1,4096/Math.max(packed.width,packed.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.ceil(packed.width*scale));c.height=Math.max(1,Math.ceil(packed.height*scale));const ctx=c.getContext('2d');ctx.scale(scale,scale);viewPieces=[];
  for(const p of packed.pieces){const ox=p.displayX-p.x,oy=p.displayY-p.y;viewPieces.push({id:p.id,triangles:p.triangles.map(t=>t.map(([u,v])=>[(u*e.texture.image.width+ox)*scale,(v*e.texture.image.height+oy)*scale]))});ctx.save();islandPath(ctx,p,e.texture.image.width,e.texture.image.height,ox,oy);ctx.clip();ctx.drawImage(e.texture.image,ox,oy);ctx.restore();if($('#texture-lines').checked){ctx.beginPath();for(const edge of p.edges){ctx.moveTo(edge[0][0]*e.texture.image.width+ox,edge[0][1]*e.texture.image.height+oy);ctx.lineTo(edge[1][0]*e.texture.image.width+ox,edge[1][1]*e.texture.image.height+oy);}ctx.strokeStyle='#ff4c90';ctx.lineWidth=3/scale;ctx.stroke();}}
  return c;
 }
 function updateIslands(){const select=$('#texture-island');select.replaceChildren(new Option('Todas as ilhas','all'),...(entry()?piecesFor(entry()):[]).map(p=>new Option(`Ilha ${p.id+1} · ${p.width} × ${p.height} px`,String(p.id))));}
 function render(){const e=entry();dialog.querySelectorAll('.texture-controls button').forEach(b=>b.disabled=!e||working);$('#texture-entry').disabled=working;$('#close-textures').disabled=working;
  const preview=$('#texture-preview');if(!e){preview.width=1;preview.height=1;$('#texture-info').textContent='Este modelo não possui texturas de imagem. Cores por vértice, como na demonstração, não possuem uma imagem para exportar.';$('#texture-notice').textContent='';positionView();return;}
  try{const layout=uvLayout(e),separated=$('#texture-mode').value==='islands',canvas=separated?islandCanvas(e,layout):canvasFor(e,$('#texture-lines').checked,true,true);$('#island-picker').hidden=!separated;for(const id of ['#download-island','#replace-island']){$(id).hidden=!separated;$(id).disabled=working||!selectedPiece()||layout.outside;}$('#texture-island').disabled=working;$('#texture-mode').disabled=working;preview.width=canvas.width;preview.height=canvas.height;preview.getContext('2d').drawImage(canvas,0,0);$('#texture-info').textContent=`${e.texture.image.width} × ${e.texture.image.height} px · ${layout.islands.length} ilhas UV`;
   $('#download-uv').disabled=working||!layout.triangles.length;$('#download-uv-svg').disabled=working||!layout.triangles.length;$('#replace-texture').disabled=working||!layout.triangles.length;$('#restore-texture').disabled=working||!originals.has(key(e));
   $('#texture-notice').textContent=[!layout.triangles.length?'Este mapa não tem coordenadas UV na malha.':'',layout.overlaps?`${layout.overlaps} triângulos têm UVs coincidentes; pintar essa região afeta múltiplas faces.`:'',layout.outside?'Há UVs fora de 0–1. A prévia mostra o tile principal; repetição/espelhamento da textura continua no modelo.':''].filter(Boolean).join(' ');
  }catch(error){$('#texture-notice').textContent=error.message;}positionView();
 }
 async function run(fn){if(working||actions.isBusy())return;working=true;actions.busy(true,'Preparando textura…');render();try{await fn();}catch(e){actions.toast(e.message,true);}finally{working=false;actions.busy(false);render();}}
 function filename(e,suffix){return `${actions.name().replace(/[^\p{L}\p{N}_-]/gu,'_')}-${e.meshIndex+1}-${e.materialIndex+1}-${e.slot}-${suffix}`;}
 async function png(canvas,name){const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw new Error('Não foi possível exportar a imagem.');actions.download(blob,name,'image/png');}
 $('#download-texture').onclick=()=>run(()=>png(canvasFor(entry(),false,true),filename(entry(),'textura.png')));
 $('#download-uv').onclick=()=>run(()=>png(canvasFor(entry(),true,false),filename(entry(),'uv.png')));
 $('#download-uv-svg').onclick=()=>run(()=>{const e=entry();actions.download(uvSVG(uvLayout(e),e.texture.image.width,e.texture.image.height),filename(e,'uv.svg'),'image/svg+xml');});
 $('#replace-texture').onclick=()=>{importPiece=null;$('#texture-file').click();};
 $('#download-island').onclick=()=>run(()=>png(cropIsland(entry().texture.image,selectedPiece()),filename(entry(),`ilha-${selectedPiece().id+1}.png`)));
 $('#replace-island').onclick=()=>{importPiece=selectedPiece();$('#texture-file').click();};$('#texture-file').onchange=()=>{const file=$('#texture-file').files[0];$('#texture-file').value='';if(!file)return;run(async()=>{
  if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>30*1024*1024)throw new Error('Use PNG, JPEG ou WebP de até 30 MB.');const e=entry(),url=URL.createObjectURL(file),image=new Image();try{image.src=url;await image.decode();if(image.width*image.height>67108864)throw new Error('Limite: 64 megapixels.');
   const replacement=e.texture.clone();replacement.source=new THREE.Source(importPiece?restoreIsland(e.texture.image,importPiece,image):image);replacement.userData={...replacement.userData,mimeType:'image/png'};replacement.needsUpdate=true;
   if(!originals.has(key(e)))originals.set(key(e),e.texture);const old=e.texture;actions.replace(e,replacement);owned.add(replacement);if(owned.has(old)){old.dispose();owned.delete(old);}e.texture=replacement;actions.toast('Textura aplicada. Salvar e Exportar GLB incluem a nova imagem.');
  }finally{URL.revokeObjectURL(url);}
 });};
 $('#restore-texture').onclick=()=>run(()=>{const e=entry(),old=e.texture,original=originals.get(key(e));if(!original)return;actions.replace(e,original);e.texture=original;originals.delete(key(e));if(owned.has(old)){old.dispose();owned.delete(old);}});
 $('#texture-mode').onchange=()=>{render();fit();};$('#texture-island').onchange=()=>{render();fit();};$('#texture-entry').onchange=()=>{updateIslands();render();fit();};$('#texture-lines').onchange=render;$('#close-textures').onclick=()=>dialog.close();dialog.addEventListener('cancel',e=>{if(working)e.preventDefault();});
 return {open(){if(actions.isBusy())return;const current=actions.asset();if(asset!==current){for(const t of originals.values())t.dispose();originals.clear();owned.clear();asset=current;}entries=textureEntries(asset);const select=$('#texture-entry');select.replaceChildren(...entries.map((e,i)=>{const option=document.createElement('option');option.value=i;option.textContent=e.label;return option;}));updateIslands();render();dialog.showModal();fit();}};
}
